# coding:utf-8
# *******************************************************************
# * Copyright 2021-present evilbinary
# * 作者: evilbinary on 01/01/20
# * 邮箱: rootdebug@163.com
# ********************************************************************
import os

Import('env')


# cflags='$CFLAGS -finstrument-functions  -finstrument-functions-exclude-function-list=do_page_fault,syscall_handler,general_protection,syscall1,syscall2,syscall3,syscall4,syscall5,print_string,do_shell_cmd,print_promot -finstrument-functions-exclude-file-list=duck/init,duck/arch,duck/libs,duck/init,duck/kernel/thread.c,duck/kernel/schedule.c,duck/kernel/syscall.c,duck/kernel/sysfn.c,duck/kernel/vfs.c,duck/kernel/devfn.c,duck/kernel/exceptions.c,duck/kernel/logger.c,duck/kernel/page.c,duck/kernel/memory.c,duck/kernel/vmemory.c'#-DUSE_POOL -finstrument-functions

cflags='$CFLAGS '

include=[
        '../',
        '../libs/include',
        '../platform',
    ]

libpath=[
    '../libs/libalgorithm/',
    '../libs/libkernel/'
]

libs=['arch',
    'archcommon',
    'algorithm',
    'kernelcommon',
    ]

env.Library('kernel', [
    'kernel.c',
    'thread.c',
    'schedule.c',
    'syscall.c',
    'exceptions.c',
    'memory.c',
    'module.c',
    'device.c',
    'vfs.c',
    'devfn.c',
    'fd.c',
    'loader.c',
    'mp.c',
    'trace.c',
    'logger.c',
    'vma.c',
    'page.c',
    'event.c'
    ],
    CPPPATH=include,
    LIBPATH=libpath,
    LIBS=libs,
    CFLAGS=cflags
    )


